# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://infinite-craft.top
title: Infinite Craft 工作室
email: infinite-craft@outlook.com
author: 卡洛Karro
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; Infinite Craft Studio 2018-2020 . <br>All Rights Reserved.'
credits: '鸣谢：登陆页面是由 <a href="http://startbootstrap.com/">创建的开源Bootstrap主题。</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: bilibili
    url: https://space.bilibili.com/358750612
  - title: github
    url: https://github.com/MrKarro
  - title: blog
    url: http://blog.infinite-craft.top/
